---
title: "Written Report"
author: "Denali Stevens"
format: html
---

# Abtract

This project pulls from a few different files all regarding information about national parks in the United States. The one I started with is a shape file provided by the National Park Service that outlines the boarders of every park unit in the country. This not only includes those with the national park title, but also every designation of a national part site (which is quite an extensive list). While this data set had some interesting information about this wide spread of areas, I was more interested in diving further into just official national parks. To find that extended information I scraped a Wikipedia page containing the 63 areas titled as national parks. All of the data provided from those data sets is included in my final app. To take the exploration a little further, I included a data set about the amount of visitors in national parks. This data set also initially contained information for every designation of national park, but I narrowed it to just those with the "national park" title to make the graph more useful.

# Introduction

This app utilizes data and visualizations to offer an opportunity for expanding knowledge about our National Parks and delivering a fundamental education about them. The shape file that I used to create the interactive map demonstrates where every park unit in the United States is and highlights where all National Parks are located. I think this does a great job of displaying not only the location, but also the size and amount of parks in the United States. The information I scraped from the National Parks Wikipedia page provided a convenient way to pose interesting questions a user can explore using the app. Some of the data that provides room for questions and exploration includes the date the park was established, its area, the state it's in, and the amount of visitors in 2022. The Wiki data also provides a brief description of each area with the title "National Park" and joining the wiki data to the nps data is what allows the user to click on these areas for more information. 

The data that I scraped from the National Parks Wikipedia page provided the best way to pose interesting questions this app can help answer and the map it provides 
* I did use chat gpt in this section to help me rephase and be consise in what I wanted to say. 
# Visualizations

# Conclusion

